# Check out https://hub.docker.com/_/node to select a new base image
FROM node:14.16.0-buster

RUN apt-get update && apt-get install -y\
    procps\
    net-tools\
    --no-install-recommends

# Set to a non-root built-in user `node`
#USER node

# Create app directory (with user `node`)
RUN mkdir -p /home/node/app

WORKDIR /home/node/app

RUN yarn global add\
    @nestjs/cli\
    typeorm