db:
  postgres: &postgres
    host: "db"
    port: 5432
    username: "postgres"
    password: "example"
    database: "cme"
  redis:
    host: "redis"
    port: 6379
    password: "96104305cdf1e02badc378cef3f60f23319d1600a6de13f71f120e476061dba3"

typeorm:
  type: "postgres"
  <<: *postgres
  entities: ["dist/apps/cme-backend/**/*.entity{.ts,.js}"]
  migrations: ["dist/migrations/*.js"]
  cli: {
      migrationsDir: "migrations"
  }
  synchronize: false
  #logging: ["error", "warn", "query"]
  logging: ["error", "warn"]

url: "http://localhost:3000"